### ISSUE TITLE
Doxygen is now broken when making new function headers inside Vue components

### ISSUE THREAD

**Issue by jonrandy** [SublimeText/Vue#40]
Since the update, new function headers with Doxygen when pressing `alt-q` are not working properly (param types not being picked up, header looking different to before).

If I switch the syntax to JS then everything with Doxygen works as before (but the highlighting for Vue is obviously then screwed)

**Comment by jonrandy** [comment]
OK, I figured it out. Looks like language changed from `js` to `jsx` - which broke Doxygen. If I make this change to the Doxygen settings, all is right again:
```js
{

    "profiles": [
        {
            "languages":  [ "js", "jsx" ], // **** added 'jsx' here ****
            "parsers":    [ "LanguageJavaScript" ],
            "doc_styles": [ "JsDoc", "GoogleClosure" ]// or "YuiDoc", "DoxyDoc", Doxygen", "ApiDoc"... according your preference
        },
    ],

}
```

**Comment by jonrandy** [comment]
Not sure if you guys need do anything?

**Comment by 20Tauri** [comment]
Thank for the report

I haven't reproduced it, but the problem seem to come from a change in JSX syntax
Adding “jsx” to the profiles means that DoxyDoxygen uses its internal JavaScript parser rather than the one based on the syntax file... JSX is JS (with extension) and internal parser prevent the plugin to be broke by syntax change (and will also improve type detection). This is a good change and I will include it in the next version

**Comment by deathaxe** [comment]
FWIW, Vue supports JSX to dynamically create templates. We could scope them `source.js` but that may cause other issues with plugins/completions relying on `source.jsx`.
